### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by AlexMeca** [RolandKovacs00/Sistem-de-recomandare-pentru-transport#5]
**Create an initial architecture including:**

- Microservice for Google API map services
- Geotools microservice for geo- spatial computation
- API Gateway
- Database to store tracking history( if needed) as part of Geotools microservice
- Frontend App including: React & Javascript mapping library(Presentation layer)

**Comment by RolandKovacs00** [comment]
![image](https://user-images.githubusercontent.com/73755909/157457666-54ee2078-6cd2-46ce-a0d0-2c7d8e8ed45f.png)
